# Generated by Django 5.2 on 2025-04-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='bytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='composer',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='milliseconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='unitPrice',
            field=models.FloatField(default=0),
        ),
    ]
