# Generated by Django 5.2 on 2025-04-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0002_album_title_artist_name_track_bytes_track_composer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
